// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type Message struct {
	ID        int64
	RoomID    int64
	UserID    sql.NullInt64
	Content   string
	SentAt    sql.NullTime
	EditedAt  sql.NullTime
	DeletedAt sql.NullTime
}

type Room struct {
	ID        int64
	Name      sql.NullString
	IsPrivate sql.NullInt64
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
}

type RoomMember struct {
	RoomID   sql.NullInt64
	UserID   sql.NullInt64
	JoinedAt sql.NullTime
	Role     sql.NullString
}

type User struct {
	ID          int64
	Username    string
	DisplayName sql.NullString
	CreatedAt   sql.NullTime
	PwHash      sql.NullString
}
